language: python
python:
    - 3.7

sudo: required
        
branches:
    - master
    - cyp
    - /^v.*$/
        
addons:
    apt:
        packages:
        - doxygen
        - graphviz
        sources:
            - ubuntu-toolchain-r-test

jobs:
  include:
    # BINARY BUILD
    - stage: Compile 
      name: "Compilation"
      - python: 3.7
        env: PLATFORMIO_CI_SRC=examples/ardref-interrupt
      - python: 3.7
        env: PLATFORMIO_CI_SRC=examples/ardref-polling
      - python: 3.7
        env: PLATFORMIO_CI_SRC=examples/lib-interrupt 
      - python: 3.7
        env:PLATFORMIO_CI_SRC=examples/lib-polling
      install: 
        - pip install -U platformio==4.1.0
        - platformio platform install -f infineonxmc@1.1.3 
        - platformio platform install -f atmelavr@2.0.0
      script: 
        - platformio ci --lib="." --board=xmc1100_xmc2go --board=xmc1100_boot_kit --board=xmc4700_relax_kit --board=uno
    # DEPLOY DOCS     
    - stage: "Deploy" 
      if: tag IS present
      name: "GitHub Pages Deployment"
      install:
        - git clone https://github.com/Infineon/InfineonDoxyGenerator.git --branch v.0.2.0
      script: 
        - cd InfineonDoxyGenerator
        - python doxyifx.py html
        - python doxyifx.py release $GH_USER $GH_PASS_TOKEN



